name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  job-name:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'

runs:
  using: 'docker'
  image: 'job_runner/Dockerfile'
  args:
    - ${{ inputs.job-name }}
