# .github/workflows/ecr-login.yml

name: ECR Login

on:
  workflow_dispatch:

jobs:
  ecr-login:
    runs-on: ubuntu-latest

    steps:
      - name: "🔧 Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-session-token: ${{ secrets.aws-session-token }}
          aws-region: ${{ secrets.aws-region }}

      - name: "🔒 Login to Amazon ECR"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
