name: Github Actions Input Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
        shell: bash

      - name: Export Secrets
        run: |
          echo "{" >> secrets.json
          for secret in $(echo "$SECRETS" | jq -r 'keys[]'); do
            echo "  \"$secret\": \"${!secret}\"," >> secrets.json
            echo "${!secret}"
          done
          echo "}" >> secrets.json
        env:
          SECRETS: ${{ toJson(secrets) }}
          NEXUS_TOKEN: ${{ secrets.NEXUS_TOKEN }}

      - name: Generate Secrets
        run: |
          echo "{" > env.json
          env | awk -F= '{print "\"" $1 "\": \"" $2 "\","}' >> env.json
          echo "}" >> env.json

      - name: Save secrets JSON
        run: |
          ls -1
          cat secrets.json
          cat env.json
        working-directory: ${{ github.workspace }}

